
import dotenv from 'dotenv';
import { createClickUpProject } from './services/clickup-service.js';
import path from 'path';
import { fileURLToPath } from 'url';

// Load env vars from parent directory
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '.env') });

async function runTest() {
    console.log('🚀 Starting ClickUp Integration Test...');

    const config = {
        apiToken: process.env.CLICKUP_API_TOKEN,
        spaceId: process.env.CLICKUP_SPACE_ID
    };

    if (!config.apiToken || !config.spaceId) {
        console.error('❌ Missing CLICKUP_API_TOKEN or CLICKUP_SPACE_ID in .env');
        process.exit(1);
    }

    const testProject = {
        clientName: '[TEST] GHL Implementation Bot',
        documentation: '# Technical Blueprint\n\nThis is a **test** blueprint generated by the integration script.',
        weeks: [
            {
                name: 'Phase 1: Foundation',
                description: 'Setting up the basics',
                tasks: [
                    {
                        name: 'Setup Subaccount',
                        description: 'Configure Twilio and Mailgun',
                        estimatedHours: 2,
                        tags: ['setup', 'urgent'],
                        metadata: { priority_ghl: 1, field_type: 'Core' }
                    },
                    {
                        name: 'Import Contacts',
                        estimatedHours: 1,
                        tags: ['data'],
                        metadata: { priority_ghl: 2 }
                    }
                ]
            },
            {
                name: 'Phase 2: Automation',
                tasks: [
                    {
                        name: 'Build Workflow',
                        estimatedHours: 3,
                        metadata: { priority_ghl: 2 }
                    }
                ]
            }
        ]
    };

    try {
        const result = await createClickUpProject(testProject, config);
        if (result.success) {
            console.log('✅ Test Passed! ClickUp Project Created.');
            console.log('Files created:', result.data.tasks.length);
            console.log('Folder URL:', result.data.folder.url || 'N/A');
        } else {
            console.error('❌ Test Failed (Functional):', result);
        }
    } catch (error) {
        console.error('❌ Test Failed (Exception):', error.message);
        if (error.response) {
            console.error('Response data:', error.response.data);
        }
    }
}

runTest();
